### PR TITLE
Update telegram channel python and add readme hints

### PR DESCRIPTION
**Pull request by benchonaut**
did not work in python-3.9  when not using docker

```
ImportError: cannot import name 'ParseMode' from 'telegram'
```
https://stackoverflow.com/questions/69155789/importerror-cannot-import-name-parsemode-from-telegram

added hints in readme to deploy non-docker environment quickly

### CODE REVIEW

**Comment by benchonaut** [comment]
( fail ..asyncio not implemented .. )
